# Generated by Django 4.2 on 2023-04-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0002_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('bio', models.TextField()),
                ('image', models.URLField(null=True)),
            ],
        ),
    ]
