# Generated by Django 4.2 on 2023-04-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0004_album_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this album', to='tunes.genre'),
        ),
    ]
